version: '3.8'

services:
  provider-test-contract:
    build:
      context: provider-clients-service
      dockerfile: Dockerfile
    command: npm run test:contract
    environment:
      - PACT_BROKER_TOKEN
      - CI
    volumes:
      - ./provider-clients-service/test:/app/test
      - ./.git:/app/.git

  consumer-test-contract:
    build:
      context: consumer-frontend
      dockerfile: Dockerfile
    command: npm run test:contract
    volumes:
      - ./pacts:/app/pacts
      - ./logs:/app/logs
