version: '3.8'

services:
  provider-test-contract:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run test:contract:provider
    environment:
      - PACT_BROKER_TOKEN
      - CI
    volumes:
      - ./test/contract:/app/test/contract

  consumer-test-contract:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run test:contract:consumer
    volumes:
      - ./pacts:/app/pacts
      - ./logs:/app/logs
