name: Integração contínua do Consumer

on:
  push:
  workflow_dispatch:

jobs:
  teste-de-contrato-do-consumer:
    runs-on: ubuntu-18.04
    name: Execução do teste de contrato do consumer
    steps:
      - name: Clone do repositório
        uses: actions/checkout@v3
      - run: docker compose run --rm consumer-test-contract
      - name: Publicar o contrato no pact-broker
        run: |
          docker run --rm \
            -w /app \
            -v ${PWD}:/app \
            -e PACT_BROKER_BASE_URL=https://danielafdc.pactflow.io \
            -e PACT_BROKER_TOKEN=${{ secrets.PACT_BROKER_TOKEN }} \
            pactfoundation/pact-cli:0.50.0.14 \
            publish \
            /app/pacts \
            --consumer-app-version ${{ github.sha }} \
            --tag-with-git-branch